const crudTypes = {
	FETCH_POSTS_START: 'FETCH_POSTS_START',
	FETCH_POSTS_SUCCESS: 'FETCH_POSTS_SUCCESS',
	FETCH_POSTS_FAILURE: 'FETCH_POSTS_FAILURE',

	ADD_POST_START: 'ADD_POST_START',
	ADD_POST_SUCCESS: 'ADD_POST_SUCCESS',
	ADD_POST_FAILURE: 'ADD_POST_FAILURE',


	ADD_COMMENT_START: 'ADD_COMMENT_START',
	ADD_COMMENT_SUCCESS: 'ADD_COMMENT_SUCCESS',
	ADD_COMMENT_FAILURE: 'ADD_COMMENT_FAILURE'

}

export default crudTypes