const crudTypes = {
	FETCH_POSTS_START: 'FETCH_POSTS_START',
	FETCH_POSTS_SUCCESS: 'FETCH_POSTS_SUCCESS',
	FETCH_POSTS_FAILURE: 'FETCH_POSTS_FAILURE',

	ADD_POST_START: 'ADD_POST_START',
	ADD_POST_SUCCESS: 'ADD_POST_SUCCESS',
	ADD_POST_FAILURE: 'ADD_POST_FAILURE',

	EDIT_CAPTION_START: 'EDIT_CAPTION_START',
	EDIT_CAPTION_FAILURE: 'EDIT_CAPTION_FAILURE',

	DELETE_POST_START: 'DELETE_POST_START',
	DELETE_POST_FAILURE: 'DELETE_POST_FAILURE',

	ADD_COMMENT_START: 'ADD_COMMENT_START',
	ADD_COMMENT_SUCCESS: 'ADD_COMMENT_SUCCESS',
	ADD_COMMENT_FAILURE: 'ADD_COMMENT_FAILURE',



	UPDATE_POST_DROPDOWN_VISIBILITY: 'UPDATE_POST_DROPDOWN_VISIBILITY',
	UPDATE_POST_EDIT_MODAL_VISIBILITY: 'UPDATE_POST_EDIT_MODAL_VISIBILITY'

}

export default crudTypes