const userTypes = {
	CHECK_USER_SESSION_START: 'CHECK_USER_SESSION_START',
	SIGN_UP_START: 'SIGN_UP_START',
	SIGN_IN_START: 'SIGN_IN_START',
	SIGN_OUT_START: 'SIGN_OUT_START',

	FETCH_USERS_START: 'FETCH_USERS_START',
	FETCH_USERS_SUCCESS: 'FETCH_USERS_SUCCESS',
	FETCH_USERS_FAILURE: 'FETCH_USERS_FAILURE',


	SIGN_OUT_SUCCESS: 'SIGN_OUT_SUCCESS',
	AUTHENTICATION_SUCCESS: 'AUTHENTICATION_SUCCESS',

	AUTHENTICATION_FAILURE: 'AUTHENTICATION_FAILURE',
	SIGN_OUT_FAILURE: 'SIGN_OUT_FAILURE',

	FOLLOW_USER_START: 'FOLLOW_USER_START',
	FOLLOW_USER_SUCCESS: 'FOLLOW_USER_SUCCESS',
	FOLLOW_USER_FAILURE: 'FOLLOW_USER_FAILURE',

	UNFOLLOW_USER_SUCCESS: 'UNFOLLOW_USER_SUCCESS',

	FETCH_FOLLOWING_START: 'FETCH_FOLLOWING_START',
	FETCH_FOLLOWING_SUCCESS: 'FETCH_FOLLOWING_SUCCESS',
	FETCH_FOLLOWING_FAILURE: 'FETCH_FOLLOWING_FAILURE',

	FETCH_FOLLOWERS_START: 'FETCH_FOLLOWERS_START',
	FETCH_FOLLOWERS_SUCCESS: 'FETCH_FOLLOWERS_SUCCESS',
	FETCH_FOLLOWERS_FAILURE: 'FETCH_FOLLOWERS_FAILURE',

	EDIT_BIO_FEATURED_START: 'EDIT_BIO_FEATURED_START',
	EDIT_BIO_FEATURED_SUCCESS: 'EDIT_BIO_FEATURED_SUCCESS',
	EDIT_BIO_FEATURED_FAILURE: 'EDIT_BIO_FEATURED_FAILURE',

	EDIT_PROFILE_START: 'EDIT_PROFILE_START',
	EDIT_PROFILE_SUCCESS: 'EDIT_PROFILE_SUCCESS',
	EDIT_PROFILE_FAILURE: 'EDIT_PROFILE_FAILURE',

}

export default userTypes
