const userTypes = {
	CHECK_USER_SESSION_START: 'CHECK_USER_SESSION_START',
	SIGN_UP_START: 'SIGN_UP_START',
	SIGN_IN_START: 'SIGN_IN_START',
	SIGN_OUT_START: 'SIGN_OUT_START',

	SIGN_OUT_SUCCESS: 'SIGN_OUT_SUCCESS',
	AUTHENTICATION_SUCCESS: 'AUTHENTICATION_SUCCESS',

	AUTHENTICATION_FAILURE: 'AUTHENTICATION_FAILURE',
	SIGN_OUT_FAILURE: 'SIGN_OUT_FAILURE'

}

export default userTypes
